[core]

# Logging level
log_level = "TRACE"

[faces]

# Size of queues in the face system
queue_size = 1024

[fw]

# Size of queues in the forwarding system
queue_size = 1024

[tables]

# Size of queues in the table system
queue_size = 1024

  [tables.dead_nonce_list]

  # Lifetime of entries in the Dead Nonce List (milliseconds)
  lifetime = 6000

  [tables.network_region]

  # List of prefixes that the forwarder is in the producer region for
  regions = []
